// <auto-generated />
using System;
using MacroViva.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MacroViva.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MacroVivaDbContext))]
    [Migration("20260709104224_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MacroViva.Domain.AIAnalysis.AIAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Model")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasDefaultValue("mock-meal-vision-v1");

                    b.Property<decimal?>("OverallConfidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("Provider")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasDefaultValue("mock");

                    b.Property<string>("RawResponseReference")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("AIAnalyses", (string)null);
                });

            modelBuilder.Entity("MacroViva.Domain.AIAnalysis.AIAnalysisItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AIAnalysisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConfidenceLevel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("ConfidenceScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<Guid?>("SuggestedFoodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SuggestedFoodName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.HasKey("Id");

                    b.HasIndex("AIAnalysisId");

                    b.ToTable("AIAnalysisItems", (string)null);
                });

            modelBuilder.Entity("MacroViva.Domain.ConsentAndPrivacy.UserConsent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConsentKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsGranted")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ConsentKey", "DecidedAt");

                    b.ToTable("UserConsents", (string)null);
                });

            modelBuilder.Entity("MacroViva.Domain.Meals.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "OccurredAt");

                    b.ToTable("Meals", (string)null);
                });

            modelBuilder.Entity("MacroViva.Domain.Meals.MealItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FoodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.ToTable("MealItems", (string)null);
                });

            modelBuilder.Entity("MacroViva.Domain.Meals.MealPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TemporaryReference")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.ToTable("MealPhotos", (string)null);
                });

            modelBuilder.Entity("MacroViva.Domain.Nutrition.Food", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("IsSupplement")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Foods", (string)null);
                });

            modelBuilder.Entity("MacroViva.Domain.Nutrition.FoodPortion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FoodId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.ToTable("FoodPortions", (string)null);
                });

            modelBuilder.Entity("MacroViva.Domain.Subscriptions.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans", (string)null);
                });

            modelBuilder.Entity("MacroViva.Domain.Subscriptions.UserSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubscriptionPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TierSnapshot")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SubscriptionPlanId");

                    b.ToTable("UserSubscriptions", (string)null);
                });

            modelBuilder.Entity("MacroViva.Domain.Supplements.Supplement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Supplements", (string)null);
                });

            modelBuilder.Entity("MacroViva.Domain.Supplements.UserSupplement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("CheckInDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Servings")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("SupplementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SupplementId", "CheckInDate");

                    b.ToTable("UserSupplements", (string)null);
                });

            modelBuilder.Entity("MacroViva.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MacroViva.Domain.Users.UserGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserGoals", (string)null);
                });

            modelBuilder.Entity("MacroViva.Domain.Users.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("MacroViva.Domain.AIAnalysis.AIAnalysisItem", b =>
                {
                    b.HasOne("MacroViva.Domain.AIAnalysis.AIAnalysis", null)
                        .WithMany("Items")
                        .HasForeignKey("AIAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MacroViva.Domain.ValueObjects.Portion", "EstimatedPortion", b1 =>
                        {
                            b1.Property<Guid>("AIAnalysisItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Grams")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("EstimatedGrams");

                            b1.Property<decimal>("Quantity")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("EstimatedQuantity");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("EstimatedUnit");

                            b1.HasKey("AIAnalysisItemId");

                            b1.ToTable("AIAnalysisItems");

                            b1.WithOwner()
                                .HasForeignKey("AIAnalysisItemId");
                        });

                    b.Navigation("EstimatedPortion")
                        .IsRequired();
                });

            modelBuilder.Entity("MacroViva.Domain.ConsentAndPrivacy.UserConsent", b =>
                {
                    b.HasOne("MacroViva.Domain.Users.User", null)
                        .WithMany("Consents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MacroViva.Domain.Meals.Meal", b =>
                {
                    b.OwnsOne("MacroViva.Domain.ValueObjects.Macronutrients", "TotalMacronutrients", b1 =>
                        {
                            b1.Property<Guid>("MealId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Calories")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("TotalCalories");

                            b1.Property<decimal>("CarbohydrateGrams")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("TotalCarbohydrateGrams");

                            b1.Property<decimal>("FatGrams")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("TotalFatGrams");

                            b1.Property<decimal>("ProteinGrams")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("TotalProteinGrams");

                            b1.HasKey("MealId");

                            b1.ToTable("Meals");

                            b1.WithOwner()
                                .HasForeignKey("MealId");
                        });

                    b.Navigation("TotalMacronutrients")
                        .IsRequired();
                });

            modelBuilder.Entity("MacroViva.Domain.Meals.MealItem", b =>
                {
                    b.HasOne("MacroViva.Domain.Meals.Meal", null)
                        .WithMany("Items")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MacroViva.Domain.ValueObjects.LocalizedName", "FoodNameSnapshot", b1 =>
                        {
                            b1.Property<Guid>("MealItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Locale")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("FoodNameSnapshotLocale");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(180)
                                .HasColumnType("nvarchar(180)")
                                .HasColumnName("FoodNameSnapshot");

                            b1.HasKey("MealItemId");

                            b1.ToTable("MealItems");

                            b1.WithOwner()
                                .HasForeignKey("MealItemId");
                        });

                    b.OwnsOne("MacroViva.Domain.ValueObjects.Macronutrients", "MacronutrientsSnapshot", b1 =>
                        {
                            b1.Property<Guid>("MealItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Calories")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("CaloriesSnapshot");

                            b1.Property<decimal>("CarbohydrateGrams")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("CarbohydrateGramsSnapshot");

                            b1.Property<decimal>("FatGrams")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("FatGramsSnapshot");

                            b1.Property<decimal>("ProteinGrams")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("ProteinGramsSnapshot");

                            b1.HasKey("MealItemId");

                            b1.ToTable("MealItems");

                            b1.WithOwner()
                                .HasForeignKey("MealItemId");
                        });

                    b.OwnsOne("MacroViva.Domain.ValueObjects.Portion", "Portion", b1 =>
                        {
                            b1.Property<Guid>("MealItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Grams")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("PortionGrams");

                            b1.Property<decimal>("Quantity")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("PortionQuantity");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("PortionUnit");

                            b1.HasKey("MealItemId");

                            b1.ToTable("MealItems");

                            b1.WithOwner()
                                .HasForeignKey("MealItemId");
                        });

                    b.Navigation("FoodNameSnapshot")
                        .IsRequired();

                    b.Navigation("MacronutrientsSnapshot")
                        .IsRequired();

                    b.Navigation("Portion")
                        .IsRequired();
                });

            modelBuilder.Entity("MacroViva.Domain.Meals.MealPhoto", b =>
                {
                    b.HasOne("MacroViva.Domain.Meals.Meal", null)
                        .WithMany("Photos")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MacroViva.Domain.Nutrition.Food", b =>
                {
                    b.OwnsOne("MacroViva.Domain.ValueObjects.LocalizedName", "Name", b1 =>
                        {
                            b1.Property<Guid>("FoodId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Locale")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("NameLocale");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(180)
                                .HasColumnType("nvarchar(180)")
                                .HasColumnName("Name");

                            b1.HasKey("FoodId");

                            b1.ToTable("Foods");

                            b1.WithOwner()
                                .HasForeignKey("FoodId");
                        });

                    b.OwnsOne("MacroViva.Domain.ValueObjects.NutritionPer100g", "NutritionPer100g", b1 =>
                        {
                            b1.Property<Guid>("FoodId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("FoodId");

                            b1.ToTable("Foods");

                            b1.WithOwner()
                                .HasForeignKey("FoodId");

                            b1.OwnsOne("MacroViva.Domain.ValueObjects.Macronutrients", "Macronutrients", b2 =>
                                {
                                    b2.Property<Guid>("NutritionPer100gFoodId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Calories")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("decimal(10,2)")
                                        .HasColumnName("CaloriesPer100g");

                                    b2.Property<decimal>("CarbohydrateGrams")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("decimal(10,2)")
                                        .HasColumnName("CarbohydrateGramsPer100g");

                                    b2.Property<decimal>("FatGrams")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("decimal(10,2)")
                                        .HasColumnName("FatGramsPer100g");

                                    b2.Property<decimal>("ProteinGrams")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("decimal(10,2)")
                                        .HasColumnName("ProteinGramsPer100g");

                                    b2.HasKey("NutritionPer100gFoodId");

                                    b2.ToTable("Foods");

                                    b2.WithOwner()
                                        .HasForeignKey("NutritionPer100gFoodId");
                                });

                            b1.Navigation("Macronutrients")
                                .IsRequired();
                        });

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("NutritionPer100g")
                        .IsRequired();
                });

            modelBuilder.Entity("MacroViva.Domain.Nutrition.FoodPortion", b =>
                {
                    b.HasOne("MacroViva.Domain.Nutrition.Food", null)
                        .WithMany("Portions")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MacroViva.Domain.ValueObjects.LocalizedName", "Name", b1 =>
                        {
                            b1.Property<Guid>("FoodPortionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Locale")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("NameLocale");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("Name");

                            b1.HasKey("FoodPortionId");

                            b1.ToTable("FoodPortions");

                            b1.WithOwner()
                                .HasForeignKey("FoodPortionId");
                        });

                    b.OwnsOne("MacroViva.Domain.ValueObjects.Portion", "Portion", b1 =>
                        {
                            b1.Property<Guid>("FoodPortionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Grams")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("Grams");

                            b1.Property<decimal>("Quantity")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("Quantity");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("Unit");

                            b1.HasKey("FoodPortionId");

                            b1.ToTable("FoodPortions");

                            b1.WithOwner()
                                .HasForeignKey("FoodPortionId");
                        });

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Portion")
                        .IsRequired();
                });

            modelBuilder.Entity("MacroViva.Domain.Subscriptions.SubscriptionPlan", b =>
                {
                    b.OwnsOne("MacroViva.Domain.ValueObjects.DateRange", "Availability", b1 =>
                        {
                            b1.Property<Guid>("SubscriptionPlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly?>("EndsOn")
                                .HasColumnType("date")
                                .HasColumnName("AvailableEndsOn");

                            b1.Property<DateOnly>("StartsOn")
                                .HasColumnType("date")
                                .HasColumnName("AvailableStartsOn");

                            b1.HasKey("SubscriptionPlanId");

                            b1.ToTable("SubscriptionPlans");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionPlanId");
                        });

                    b.OwnsOne("MacroViva.Domain.ValueObjects.LocalizedName", "Name", b1 =>
                        {
                            b1.Property<Guid>("SubscriptionPlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Locale")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("NameLocale");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("Name");

                            b1.HasKey("SubscriptionPlanId");

                            b1.ToTable("SubscriptionPlans");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionPlanId");
                        });

                    b.OwnsOne("MacroViva.Domain.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("SubscriptionPlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("PriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("PriceCurrency");

                            b1.HasKey("SubscriptionPlanId");

                            b1.ToTable("SubscriptionPlans");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionPlanId");
                        });

                    b.Navigation("Availability")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("MacroViva.Domain.Subscriptions.UserSubscription", b =>
                {
                    b.OwnsOne("MacroViva.Domain.ValueObjects.DateRange", "ActivePeriod", b1 =>
                        {
                            b1.Property<Guid>("UserSubscriptionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly?>("EndsOn")
                                .HasColumnType("date")
                                .HasColumnName("ActiveEndsOn");

                            b1.Property<DateOnly>("StartsOn")
                                .HasColumnType("date")
                                .HasColumnName("ActiveStartsOn");

                            b1.HasKey("UserSubscriptionId");

                            b1.ToTable("UserSubscriptions");

                            b1.WithOwner()
                                .HasForeignKey("UserSubscriptionId");
                        });

                    b.OwnsOne("MacroViva.Domain.ValueObjects.Money", "PriceSnapshot", b1 =>
                        {
                            b1.Property<Guid>("UserSubscriptionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("PriceSnapshotAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("PriceSnapshotCurrency");

                            b1.HasKey("UserSubscriptionId");

                            b1.ToTable("UserSubscriptions");

                            b1.WithOwner()
                                .HasForeignKey("UserSubscriptionId");
                        });

                    b.Navigation("ActivePeriod")
                        .IsRequired();

                    b.Navigation("PriceSnapshot")
                        .IsRequired();
                });

            modelBuilder.Entity("MacroViva.Domain.Supplements.Supplement", b =>
                {
                    b.OwnsOne("MacroViva.Domain.ValueObjects.Macronutrients", "MacronutrientsPerServing", b1 =>
                        {
                            b1.Property<Guid>("SupplementId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Calories")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("CaloriesPerServing");

                            b1.Property<decimal>("CarbohydrateGrams")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("CarbohydrateGramsPerServing");

                            b1.Property<decimal>("FatGrams")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("FatGramsPerServing");

                            b1.Property<decimal>("ProteinGrams")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("ProteinGramsPerServing");

                            b1.HasKey("SupplementId");

                            b1.ToTable("Supplements");

                            b1.WithOwner()
                                .HasForeignKey("SupplementId");
                        });

                    b.OwnsOne("MacroViva.Domain.ValueObjects.LocalizedName", "Name", b1 =>
                        {
                            b1.Property<Guid>("SupplementId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Locale")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("NameLocale");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(180)
                                .HasColumnType("nvarchar(180)")
                                .HasColumnName("Name");

                            b1.HasKey("SupplementId");

                            b1.ToTable("Supplements");

                            b1.WithOwner()
                                .HasForeignKey("SupplementId");
                        });

                    b.Navigation("MacronutrientsPerServing")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("MacroViva.Domain.Supplements.UserSupplement", b =>
                {
                    b.OwnsOne("MacroViva.Domain.ValueObjects.Macronutrients", "MacronutrientImpact", b1 =>
                        {
                            b1.Property<Guid>("UserSupplementId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Calories")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("ImpactCalories");

                            b1.Property<decimal>("CarbohydrateGrams")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("ImpactCarbohydrateGrams");

                            b1.Property<decimal>("FatGrams")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("ImpactFatGrams");

                            b1.Property<decimal>("ProteinGrams")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("ImpactProteinGrams");

                            b1.HasKey("UserSupplementId");

                            b1.ToTable("UserSupplements");

                            b1.WithOwner()
                                .HasForeignKey("UserSupplementId");
                        });

                    b.Navigation("MacronutrientImpact")
                        .IsRequired();
                });

            modelBuilder.Entity("MacroViva.Domain.Users.UserGoal", b =>
                {
                    b.HasOne("MacroViva.Domain.Users.User", null)
                        .WithOne("Goal")
                        .HasForeignKey("MacroViva.Domain.Users.UserGoal", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MacroViva.Domain.ValueObjects.DailyTargets", "DailyTargets", b1 =>
                        {
                            b1.Property<Guid>("UserGoalId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("UserGoalId");

                            b1.ToTable("UserGoals");

                            b1.WithOwner()
                                .HasForeignKey("UserGoalId");

                            b1.OwnsOne("MacroViva.Domain.ValueObjects.Macronutrients", "TargetMacronutrients", b2 =>
                                {
                                    b2.Property<Guid>("DailyTargetsUserGoalId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Calories")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("decimal(10,2)")
                                        .HasColumnName("TargetCalories");

                                    b2.Property<decimal>("CarbohydrateGrams")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("decimal(10,2)")
                                        .HasColumnName("TargetCarbohydrateGrams");

                                    b2.Property<decimal>("FatGrams")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("decimal(10,2)")
                                        .HasColumnName("TargetFatGrams");

                                    b2.Property<decimal>("ProteinGrams")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("decimal(10,2)")
                                        .HasColumnName("TargetProteinGrams");

                                    b2.HasKey("DailyTargetsUserGoalId");

                                    b2.ToTable("UserGoals");

                                    b2.WithOwner()
                                        .HasForeignKey("DailyTargetsUserGoalId");
                                });

                            b1.Navigation("TargetMacronutrients")
                                .IsRequired();
                        });

                    b.Navigation("DailyTargets")
                        .IsRequired();
                });

            modelBuilder.Entity("MacroViva.Domain.Users.UserProfile", b =>
                {
                    b.HasOne("MacroViva.Domain.Users.User", null)
                        .WithOne("Profile")
                        .HasForeignKey("MacroViva.Domain.Users.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MacroViva.Domain.ValueObjects.LocalizedName", "DisplayName", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Locale")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("DisplayNameLocale");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("nvarchar(160)")
                                .HasColumnName("DisplayName");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("UserProfiles");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");
                        });

                    b.OwnsOne("MacroViva.Domain.ValueObjects.BodyMetrics", "BodyMetrics", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal?>("BodyFatPercentage")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("BodyFatPercentage");

                            b1.Property<decimal>("HeightCm")
                                .HasPrecision(8, 2)
                                .HasColumnType("decimal(8,2)")
                                .HasColumnName("HeightCm");

                            b1.Property<decimal>("WeightKg")
                                .HasPrecision(8, 2)
                                .HasColumnType("decimal(8,2)")
                                .HasColumnName("WeightKg");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("UserProfiles");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");
                        });

                    b.Navigation("BodyMetrics");

                    b.Navigation("DisplayName")
                        .IsRequired();
                });

            modelBuilder.Entity("MacroViva.Domain.AIAnalysis.AIAnalysis", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MacroViva.Domain.Meals.Meal", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("MacroViva.Domain.Nutrition.Food", b =>
                {
                    b.Navigation("Portions");
                });

            modelBuilder.Entity("MacroViva.Domain.Users.User", b =>
                {
                    b.Navigation("Consents");

                    b.Navigation("Goal");

                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
